name: Build & Deploy

on:
  push:
    branches: ["development"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          SCRIPT: |
            cd /root/ximi-server
            git pull origin development
            /root/.local/share/pnpm/pnpm install
            /root/.nvm/versions/node/v18.9.1/bin/node swagger.js
            /root/.local/share/pnpm/pnpm run build
            docker build -t ximi-server .
            docker-compose down
            docker-compose up -d
